### ISSUE TITLE
样式画廊不能正确显示

### ISSUE THREAD

**Issue by feihu21** [haiiliin/pyqtribbon#100]
我使用python3.11.4，pyqt6的版本为6.4.2时，运行带有样式画廊时，界面不能正常显示。不知道是什么问题。
![样式画廊](https://github.com/user-attachments/assets/6106912f-fd35-4473-9361-70ddc1aa3483)

**Comment by haiiliin** [comment]
这是个bug，我之前也发现了，还没时间着手解决

**Comment by haiiliin** [comment]
该 Bug 由 dbb5407a403dcc3dcb5dbcb9bebe67ae7b24cfa1 导致，只有版本 `v0.7.6` 会受到影响

**Comment by feihu21** [comment]
好的，非常感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hailin ***@***.***&gt;; 
发送时间: 2024年9月5日(星期四) 晚上6:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haiiliin/pyqtribbon] 样式画廊不能正确显示 (Issue #100)














 
该 Bug 由 dbb5407 导致，只有版本 v0.7.6 会受到影响
