### ISSUE TITLE
[Request]: specify PyQt5 version (preferably 5.9)

### ISSUE THREAD

**Issue by Diogo-Rossi** [haiiliin/pyqtribbon#40]
If it is possible, please, specify a version of PyQt5, preferably == 5.9

Anaconda python distribution is frozen in PyQt5 5.9 ([link 1](https://github.com/ContinuumIO/anaconda-issues/issues/9124#issuecomment-379703990), [link 2](https://github.com/ContinuumIO/anaconda-issues/issues/11183#issuecomment-518822063))

**Comment by haiiliin** [comment]
Do you mean this package did not work on PyQt 5.9? I am not really sure about this, I never tested it in PyQt 5.9, I am using PyQt 5.15.

**Comment by Diogo-Rossi** [comment]
> Do you mean this package did not work on PyQt 5.9? I am not really sure about this, I never tested it in PyQt 5.9, I am using PyQt 5.15.

When I tried to install it, it automatically updated PyQt package to the last, PyQt 5.15. And that somehow broke the Anaconda environment. I don't know if there is a way to prevent this update (something like `>= 5.9`)

**Comment by haiiliin** [comment]
Oh I know, maybe we should remove the `PyQt5` hard requirement in `setup.py`, and user should should to install one of `PyQt5`, `PyQt6`, `PySide2`, or `PySide6` package.

**Comment by beenfrog** [comment]
You can use `pip install --no-dependencies pyqtribbon` without affecting any pre-existing PyQt5 packages.

**Comment by haiiliin** [comment]
Published a new version v0.5.0 to remove the PyQt5 requirement.
