### ISSUE TITLE
AttributeError: type object 'Qt' has no attribute 'Alignment'

### ISSUE THREAD

**Issue by ovo-Tim** [haiiliin/pyqtribbon#49]
I used `pip install git+https://github.com/haiiliin/pyqtribbon.git@main` to install it.
This is my code:
``` python
import sys
import os
os.environ['QT_API'] = 'pyside2'

from qtpy import QtGui
from qtpy.QtWidgets import QApplication, QMainWindow
from qtpy.QtGui import QIcon

from pyqtribbon import RibbonBar, RibbonCategoryStyle
from pyqtribbon.screenshotwindow import RibbonScreenShotWindow
```
However, I get the following error:
``` bash
File "/home/tim/mambaforge/lib/python3.10/site-packages/pyqtribbon/menu.py", line 93, in RibbonMenu
    def addLabel(self, text: str = "", alignment: QtCore.Qt.Alignment = QtCore.Qt.AlignLeft):
AttributeError: type object 'Qt' has no attribute 'Alignment'
```
What should I do?

**Comment by haiiliin** [comment]
Which PyQt/PySide version are you using?

**Comment by ovo-Tim** [comment]
Maybe, The problem is my environment setting.Thanks for your help.Please delete this issues :smiley:

**Comment by haiiliin** [comment]
It seems that for different PyQt/PySide distributions, the API for `QtCore.Qt.Alignment` is different, the current code only works on `PyQt5` and `PySide2`, but does not work on `PyQt6` and `PySide6`

**Comment by haiiliin** [comment]
> Maybe, The problem is my environment setting.Thanks for your help.Please delete this issues 😃

This is actually a bug, I will fix it in #50 and publish a patch version.

**Comment by haiiliin** [comment]
> It seems that for different PyQt/PySide distributions, the API for `QtCore.Qt.Alignment` is different, the current code only works on `PyQt5` and `PySide2`, but does not work on `PyQt6` and `PySide6`

Actually only it only occurs in `PyQt6`.

**Comment by haiiliin** [comment]
pyqtribbon version `0.6.2` has been released
