### ISSUE TITLE
All area of the first tab is not clickable 

### ISSUE THREAD

**Issue by TheInevitable360** [haiiliin/pyqtribbon#58]
I am adding tabs and panels to the ribbon through the dictionary. there is a tiny bug on the first Tab. When I hover my mouse over other tabs they can be selected so the corresponding tab will be opened but for the first tab, all area is not clickable. Only a very narrow section below the tab title and on the right side can be clicked. 

![ribbon](https://user-images.githubusercontent.com/81265123/229764903-1add4e25-efc8-4720-ba86-8d891adb4b63.gif)

**Comment by haiiliin** [comment]
Can you provide the source code of this example?

**Comment by TheInevitable360** [comment]
from PyQt5.QtWidgets import QMainWindow, QApplication
    from pyqtribbon import RibbonBar, RibbonCategoryStyle
    	    
    class MainWindow(QMainWindow):
    
        def __init__(self):
            super().__init__()
     
     
            self.setGeometry(600, 200, 800, 800)
     
     
            ribbon = RibbonBar()
     
            categories = {
                "Tab1":{
                    "style": RibbonCategoryStyle.Normal,
                    "panels": {}
                },
     
                "Tab2": {
                    "style": RibbonCategoryStyle.Normal,
                    "panels": {}
                },
     
                "Tab3": {
                    "style": RibbonCategoryStyle.Normal,
                    "panels": {}
                },
     
                "Tab4": {
                    "style": RibbonCategoryStyle.Normal,
                    "panels": {}
                },
     
                "Tab5": {
                    "style": RibbonCategoryStyle.Normal,
                    "panels": {}
                }
            }
            ribbon.addCategoriesBy(categories)
     
            self.setMenuBar(ribbon)
     
    
    
    
    if __name__ == "__main__":
        app = QApplication([])
        main_winodw = MainWindow()
        main_winodw.show()
        app.exec()

**Comment by TheInevitable360** [comment]
I upgraded to the latest version wich is 0.7.1 and issue has been resolved :)
