### ISSUE TITLE
大佬，能支持Pyside2吗？😂

### ISSUE THREAD

**Issue by wanghuqiang123** [haiiliin/pyqtribbon#63]

**Comment by haiiliin** [comment]
正常情况下应该是支持PySide2的，我在三个平台都进行了测试的。有什么问题你可以贴出来我看看

**Comment by wanghuqiang123** [comment]
> 正常情况下应该是支持PySide2的，我在三个平台都进行了测试的。有什么问题你可以贴出来我看看

系统环境：Windows11
IDE：PyCharm
Python version：3.8

问题：我在阅读文档后按照“Customize Panels”的Example实例代码  我将window改为了PySide2导入的QMainWindow

`from PySide2.QtWidgets import  QMainWindow
import sys
from qtpy import QtGui
from qtpy.QtWidgets import QApplication, QToolButton, QMenu, QLabel, QLineEdit
from qtpy.QtGui import QIcon
from qtpy.QtCore import Qt

from pyqtribbon import RibbonBar
from pyqtribbon.screenshotwindow import RibbonScreenShotWindow

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setFont(QtGui.QFont("Times New Roman", 8))
    window = QMainWindow()

    # Ribbon bar
    ribbonbar = RibbonBar()
    window.setMenuBar(ribbonbar)

    category1 = ribbonbar.addCategory("Category 1")
    panel = category1.addPanel("Panel 1", showPanelOptionButton=False)
    panel.addSmallButton("Button 1", icon=QIcon("python.png"))
    panel.addSmallButton("Button 2", icon=QIcon("python.png"))
    panel.addSmallButton("Button 3", icon=QIcon("python.png"))
    panel.addMediumToggleButton("Show/Hide Category 2", icon=QIcon("python.png"))
    panel.addVerticalSeparator()
    panel.addMediumToggleButton("Show/Hide Category 3", icon=QIcon("python.png"))
    panel.addMediumToggleButton("Show/Hide Category 4/5", icon=QIcon("python.png"), colSpan=2, alignment=Qt.AlignLeft)
    panel.addLargeButton("Button 4", icon=QIcon("python.png"))
    panel.addVerticalSeparator()
    panel.addMediumButton("Button 5", icon=QIcon("python.png"))
    panel.addMediumButton("Button 6", icon=QIcon("python.png"))

    button = panel.addLargeButton("Button 7", icon=QIcon("python.png"))
    menu = QMenu()
    menu.addAction(QIcon("python.png"), "Action 1")
    menu.addAction(QIcon("python.png"), "Action 2")
    menu.addAction(QIcon("python.png"), "Action 3")
    button.setMenu(menu)
    button.setPopupMode(QToolButton.InstantPopup)
    panel.addWidget(button, rowSpan=6)

    gallery = panel.addGallery(minimumWidth=500, popupHideOnClick=True)
    for i in range(100):
        gallery.addToggleButton(f'item {i+1}', QIcon("python.png"))
    popupMenu = gallery.popupMenu()
    submenu = popupMenu.addMenu(QIcon("python.png"), 'Submenu')
    submenu.addAction(QIcon("python.png"), "Action 4")
    popupMenu.addAction(QIcon("python.png"), "Action 1")
    popupMenu.addAction(QIcon("python.png"), "Action 2")
    popupMenu.addSeparator()
    popupMenu.addWidget(QLabel("This is a custom widget"))
    formLayout = popupMenu.addFormLayoutWidget()
    formLayout.addRow(QLabel("Row 1"), QLineEdit())

    # Show the window
    window.resize(1300, 250)
    window.show()

    sys.exit(app.exec_())`


结果
开始运行后报错:
Traceback (most recent call last):
  File "D:\Install_File\python3_7\lib\site-packages\pyqtribbon\menu.py", line 116, in actionEvent
    self.actionAdded.emit(a0.action())  # type: ignore
AttributeError: 'PySide2.QtGui.QActionEvent' object has no attribute 'action'

但是报完错界面还是运行起来了

**Comment by haiiliin** [comment]
这个应该是 PySide2 的一个 Bug，https://bugreports.qt.io/browse/PYSIDE-821

**Comment by haiiliin** [comment]
> 这个应该是 PySide2 的一个 Bug，https://bugreports.qt.io/browse/PYSIDE-821

使用 `PyQt5`/`PyQt6`/`PySide6` 应该都没有问题

**Comment by wanghuqiang123** [comment]
好的，谢谢大佬👍

**Comment by haiiliin** [comment]
## Issues on `PySide2` for `QActionEvent`

Relevant Code:
```python
def actionEvent(self, a0: QtGui.QActionEvent) -> None:
    if a0.type() == QtGui.QActionEvent.ActionAdded:
        self.actionAdded.emit(a0.action())  # type: ignore
    super().actionEvent(a0)
```
Error Message:
`PySide2.QtGui.QActionEvent has no attribute action()`

**Comment by wanghuqiang123** [comment]
大佬，想再请教一下，applicationButton可以去掉吗，我看文档的时候好像没有remove  application button的相关接口函数

**Comment by haiiliin** [comment]
> 大佬，想再请教一下，applicationButton可以去掉吗，我看文档的时候好像没有remove application button的相关接口函数

`ribbon._titleWidget._quickAccessToolBar.removeAction(ribbon._titleWidget._quickAccessToolBar.actions()[0])`

**Comment by haiiliin** [comment]
等待 PR#64 合并后，应该就可以在 PySide2 上使用了。

**Comment by haiiliin** [comment]
版本 0.7.3 已发布，PySide2 应该可以使用了
