### ISSUE TITLE
ribbon.collapseRibbonButton().hide() setHide(True) setVisible(False),都不起作用

### ISSUE THREAD

**Issue by eclosion2012** [haiiliin/pyqtribbon#80]

**Comment by haiiliin** [comment]
使用 `ribbon.hideRibbon()`

**Comment by haiiliin** [comment]
如果你想移除右侧的按钮，使用：
```python
ribbon._titleWidget._rightToolBar.removeAction(ribbon._titleWidget._rightToolBar.actions()[0])
```

**Comment by eclosion2012** [comment]
我试下，现在用的ribbonbar.helpRibbonButton().setFixedSize(0,0)




雪落无声
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haiiliin/pyqtribbon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haiiliin/pyqtribbon] ribbon.collapseRibbonButton().hide() setHide(True) setVisible(False),都不起作用 (Issue #80)





 
如果你想移除右侧的按钮，使用：
 ribbon._titleWidget._rightToolBar.removeAction(ribbon._titleWidget._rightToolBar.actions()[0])
