### ISSUE TITLE
有pyside 6的example吗 只看到pyqt的示例

### ISSUE THREAD

**Issue by VanilaMao** [haiiliin/pyqtribbon#84]
有pyside 6的example吗 只看到pyqt的示例

**Comment by haiiliin** [comment]
示例用的qtpy，按理来说应该是兼容pyside6的

**Comment by VanilaMao** [comment]
source code的实现使用的pyqt， 不知道如何兼容pyside 6

**Comment by haiiliin** [comment]
代码里面用的都是qtpy，你只要安装pyside6不安装pyqt就直接能用pyside6运行

**Comment by VanilaMao** [comment]
可以根据这篇文章让这个laibrary support both pyside6 and pyqt6 吗？ https://www.pythonguis.com/faq/pyqt6-vs-pyside6/

**Comment by haiiliin** [comment]
> 可以根据这篇文章让这个laibrary support both pyside6 and pyqt6 吗？ https://www.pythonguis.com/faq/pyqt6-vs-pyside6/

这就是 qtpy 干的事呀
